# Generated by Django 2.2.6 on 2021-02-21 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=50, null=True)),
                ('x', models.CharField(blank=True, max_length=50, null=True)),
                ('y', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='VideoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(max_length=50)),
                ('caption', models.CharField(blank=True, max_length=2200, null=True)),
                ('vid_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('location_id', models.IntegerField(blank=True, max_length=50, null=True)),
                ('thump_offset', models.IntegerField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(max_length=2000)),
                ('date_pub', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PhotoPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(max_length=50)),
                ('caption', models.CharField(blank=True, max_length=2200, null=True)),
                ('img_url', models.URLField(blank=True, max_length=4000, null=True)),
                ('location_id', models.IntegerField(blank=True, max_length=50, null=True)),
                ('token', models.CharField(max_length=2000)),
                ('date_pub', models.IntegerField()),
                ('user_tags', models.ManyToManyField(to='posts.UserTag')),
            ],
        ),
    ]
