# Generated by Django 2.2.6 on 2021-02-21 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='img_url',
            field=models.CharField(blank=True, max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='location_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='photopost',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.RemoveField(
            model_name='photopost',
            name='user_tags',
        ),
        migrations.AddField(
            model_name='photopost',
            name='user_tags',
            field=models.CharField(blank=True, max_length=2200, null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='location_id',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='thump_offset',
            field=models.IntegerField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='user_id',
            field=models.BigIntegerField(),
        ),
        migrations.DeleteModel(
            name='UserTag',
        ),
    ]
