# Generated by Django 2.2.6 on 2021-02-21 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210221_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='location_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='location_id',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='thump_offset',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
