# Generated by Django 2.2.6 on 2021-02-22 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20210221_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photopost',
            name='date_pub',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='videopost',
            name='date_pub',
            field=models.BigIntegerField(),
        ),
    ]
