# Generated by Django 2.2.6 on 2021-03-31 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='schedule_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
